- id: "NuGet::Microsoft.AspNetCore.Grpc.Swagger:[7.0.0,)"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/Grpc/JsonTranscoding/src/Microsoft.AspNetCore.Grpc.Swagger"
